name: MADE Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  made-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Create kaggle.json
        run: |
          echo '{"username": "${{ secrets.KAGGLE_USERNAME }}", "key": "${{ secrets.KAGGLE_KEY }}"}' > kaggle.json
      
      - name: Install Python dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt
          python -m pip install --upgrade kaggle

      - name: Run MADE Pipeline
        run: 
            bash project/pipeline.sh
            
      - name: Run MADE Automated test
        run: 
            bash project/test.sh
